### PR TITLE
Problem: Netty is missing from todolist's dependencies

### PR DESCRIPTION
**Pull request by stuarth**
Solution: Add missing Netty dependencies to build.gradle

### CODE REVIEW

**Comment by yrashk** [comment]
Won't those come through pumpkindb-client, though?

**Comment by stuarth** [comment]
Received this prior to PR

https://gist.github.com/stuarth/e8de2bd9abc7bb5b4a3fdcaa70a51f97

**Comment by yrashk** [comment]
Interesting. Did you run `gradle publishToMavenLocal` for the client library itself (in the root of the repo)?

**Comment by stuarth** [comment]
I ran what I imagine is the equivalent mvn (gradle is foreign to me)

```
mvn install:install-file -Dfile=build/libs/pumpkindb-client-0.1.jar "-DgroupId=org.pumpkindb" "-DartifactId=pumpkindb-client" -Dversion=0.1 -Dpackaging=jar
```

**Comment by stuarth** [comment]
You're right, installing with `gradle publishToMavenLocal` resolves

**Comment by yrashk** [comment]
👍 perhaps we should amend examples' README to make sure people don't run into this issue anymore.

**Pull request closed without merging**
